site_name: llm_app_test Documentation
site_description: A semantic testing framework for LLM applications
site_url: https://Shredmetal.github.io/llmtest/
repo_url: https://github.com/Shredmetal/llmtest
repo_name: llm_app_test

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Guides:
    - Best Practices: guides/best-practices.md
    - CI/CD Integration: guides/ci-cd.md
    - Testing Patterns: guides/testing-patterns.md
  - API Reference:
    - BehavioralAssertion: api/behavioral-assertion.md
    - Custom Prompt Injection: api/custom-prompt-injection.md
    - Configuration: api/configuration.md
    - Error Handling: api/error-handling.md
  - Reliability Testing:
      - Format Compliance: reliability_testing/format_compliance.md
      - Semantic Reliability: reliability_testing\behavioral_testing_reliability.md
      - Semantic Boundary Analysis: reliability_testing\behavior_at_semantic_boundaries.md