site_name: llm_app_test Documentation
site_description: A behavioral testing library for LLM applications that allows developers to write natural language specifications for unit and integration tests. Validate LLM application behavior using plain English assertions in a simple assert(str, str) form factor.
site_url: https://Shredmetal.github.io/llmtest/
repo_url: https://github.com/Shredmetal/llmtest
repo_name: llm_app_test

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  - Guides:
      - Best Practices: guides/best-practices.md
      - CI/CD Integration: guides/ci-cd.md
      - Testing Patterns: guides/testing-patterns.md
      - Testing Hierarchy: guides/testing-hierarchy.md
  - API Reference:
      - BehavioralAssertion: api/behavioral-assertion.md
      - Custom Prompt Configuration: api/custom-prompt-configuration.md
      - Configuration: api/configuration.md
      - Error Handling: api/error-handling.md
      - Rate Limiter: api/rate-limiter.md
  - Reliability Testing:
      - Format Compliance: reliability_testing/format_compliance.md
      - Behavioral Matching Reliability: reliability_testing/behavioral_testing_reliability.md
      - Behavioral Matching at Semantic Boundary Analysis: reliability_testing/behavior_at_semantic_boundaries.md