site_name: llmtest Documentation
site_description: A semantic testing framework for LLM applications
site_url: https://Shredmetal.github.io/llmtest/
repo_url: https://github.com/Shredmetal/llmtest
repo_name: llmtest

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Guides:
    - Best Practices: guides/best-practices.md
    - CI/CD Integration: guides/ci-cd.md
  - API Reference:
    - SemanticAssertion: api/semantic-assertion.md
    - Configuration: api/configuration.md
